# Generated by Django 3.0.5 on 2020-11-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201026_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='np',
            old_name='adsl',
            new_name='fo_plan',
        ),
        migrations.RenameField(
            model_name='np',
            old_name='evdo',
            new_name='ftth_b',
        ),
        migrations.RenameField(
            model_name='np',
            old_name='fourg',
            new_name='gen2',
        ),
        migrations.RenameField(
            model_name='np',
            old_name='ftthb',
            new_name='gen3',
        ),
        migrations.RenameField(
            model_name='np',
            old_name='lte',
            new_name='gen4',
        ),
        migrations.RenameField(
            model_name='np',
            old_name='popul',
            new_name='population',
        ),
        migrations.RenameField(
            model_name='np',
            old_name='satellite',
            new_name='project3g4g250',
        ),
        migrations.RenameField(
            model_name='np',
            old_name='threeg',
            new_name='radiomonitoring',
        ),
        migrations.RenameField(
            model_name='np',
            old_name='twog',
            new_name='ruraldistrict',
        ),
        migrations.RemoveField(
            model_name='np',
            name='vols',
        ),
    ]
